<?php

/**
 * @file
 * Módulo Forcontu Test Project
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function forcontu_test_project_help($route_name,\Drupal\Core\Routing\RouteMatchInterface $route_match) {
    
  switch ($route_name) {
    case 'help.page.forcontu_test_project':
      $output = '';
      $output .= '<h3>' . t('Testing git' ) . '</h3>';
      $output .= '<p>' . t('Testing git with Drupal projects. ' ) . '</p>';
    return $output;
  }
}