<?php

/**
* @file
* Contains install and update functions for Forcontu Test Project.
*/

use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_install().
 */
function forcontu_test_project_install(){
 
  \Drupal::state()->set('forcontu_test_project.test', TRUE);
 
  $term = Term:: create([
    'name' => t('Forcontu Test' ),
    'vid' => 'tags' ,
  ]);
  $term->save();
  
}

/**
 * Implements hook_uninstall().
 */
function forcontu_hello_uninstall(){
	
  \Drupal::state()->delete('forcontu_test_project.test');
  
}